## Creates file with history data

In [1]:
import pandas as pd
from pandas import DataFrame
import numpy as np
import datetime
from datetime import timedelta
import math
pd.set_option('display.max_columns', 100)

* Создадим датасет с историей добычи он будет использоваться для загрузки в модель

In [13]:
#'PRODUCTION DATA/IPE1b.OBS' original data
# пересохранил его в xlsx
path = 'PRODUCTION DATA/OBS.xlsx'
df_hist= pd.read_excel(path)
print(df_hist.shape)
df_hist.head()

(96, 69)

,TIME,WBHP:WELL1,WBHP:WELL1A,WBHP:WELL1B,WBHP:WELL9,WBHP:WELL4,WBHP:WELL4A,WBHP:WELL6,WBHP:WELL8,WBHP:WELL3,WBHP:WELL3A,WBHP:WELL2,WBHP:WELL2A,WBHP:WELL5,WBHP:WELL5A,WBHP:WELL7,WBHP:WELL10,WOPR:WELL1,WOPR:WELL1A,WOPR:WELL1B,WOPR:WELL9,WOPR:WELL4,WOPR:WELL4A,WOPR:WELL6,WOPR:WELL8,WOPR:WELL3,WOPR:WELL3A,WOPR:WELL2,WOPR:WELL2A,WOPR:WELL5,WOPR:WELL5A,WOPR:WELL7,WOPR:WELL10,WWPR:WELL1,WWPR:WELL1A,WWPR:WELL1B,WWPR:WELL9,WWPR:WELL4,WWPR:WELL4A,WWPR:WELL6,WWPR:WELL8,WWPR:WELL3,WWPR:WELL3A,WWPR:WELL2,WWPR:WELL2A,WWPR:WELL5,WWPR:WELL5A,WWPR:WELL7,WWPR:WELL10,FGPR,FOPR,FWPR,FWCT,FWIR,WGPR:WELL1A,WGPR:WELL1B,WGPR:WELL9,WGPR:WELL4,WGPR:WELL4A,WGPR:WELL6,WGPR:WELL8,WGPR:WELL3,WGPR:WELL3A,WGPR:WELL2,WGPR:WELL2A,WGPR:WELL5,WGPR:WELL5A,WGPR:WELL7,WGPR:WELL10
0,31,2236.946357,2056.431104,2166.392038,2398.164917,2099.967864,2092.965638,2161.395775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7946.073372,8128.736957,7751.562887,6187.073777,8280.550662,8131.830260,8076.498701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,14.639098,56.491135,5.289310,8.362675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18161.49557,54570.17139,399.106784,0.004437,0.00000,2840.897487,2741.539860,2221.936400,2795.228588,2876.195897,2678.222242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8196.885023,7977.844973,8113.299721,6584.080705,7829.818046,8230.251332,7603.097992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.680479,0.000000,9.324531,10.000665,4.138146,1.195497,0.352145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19390.39938,53296.76918,0.000000,0.005430,99143.25200,2915.183018,2846.788616,2273.507914,2757.570995,2746.184107,2902.789375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7888.974902,7951.103058,7889.247859,6567.626397,8223.475231,8283.064223,8249.135106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,20.492132,0.000000,29.489170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19667.95027,55948.69065,13.924788,0.000000,92393.05187,2768.417013,2880.805791,2369.507715,2782.917414,2668.617685,2813.077959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8040.342778,7773.603514,7939.935350,6735.781471,7920.414343,8391.883093,8361.097520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.393044,0.000000,0.000000,0.000000,0.000000,2.278235,29.409356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20941.09969,58306.74660,0.000000,0.004773,98899.73279,2915.423672,2683.127535,2262.932487,2864.713814,2872.642484,2871.503929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8206.164825,8367.572056,8102.220248,6520.983647,7983.917399,7788.655852,8361.199849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.307177,3.807105,1.806913,64.874813,1.726002,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18460.27350,50139.59676,0.000000,0.000000,101695.06180,2832.062119,2832.831532,2226.899012,2805.570510,2740.679287,2787.114345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# показывает какие значения хедера содержат какие данные
header = df_hist.columns.values
print('The number of columns in dataframe is', len(header))
print(sorted(header[:1])) # ['TIME']
print(sorted(header[1:17])) # WBHP
print(sorted(header[17:33])) # WOP
print(sorted(header[33:49])) # WWPR
print(sorted(header[55:])) # WGPR there is no 'WGPR:WELL1'
print(sorted(header[49:54])) # FIELD

The number of columns in dataframe is 69
['TIME']
['WBHP:WELL1', 'WBHP:WELL10', 'WBHP:WELL1A', 'WBHP:WELL1B', 'WBHP:WELL2', 'WBHP:WELL2A', 'WBHP:WELL3', 'WBHP:WELL3A', 'WBHP:WELL4', 'WBHP:WELL4A', 'WBHP:WELL5', 'WBHP:WELL5A', 'WBHP:WELL6', 'WBHP:WELL7', 'WBHP:WELL8', 'WBHP:WELL9']
['WOPR:WELL1', 'WOPR:WELL10', 'WOPR:WELL1A', 'WOPR:WELL1B', 'WOPR:WELL2', 'WOPR:WELL2A', 'WOPR:WELL3', 'WOPR:WELL3A', 'WOPR:WELL4', 'WOPR:WELL4A', 'WOPR:WELL5', 'WOPR:WELL5A', 'WOPR:WELL6', 'WOPR:WELL7', 'WOPR:WELL8', 'WOPR:WELL9']
['WWPR:WELL1', 'WWPR:WELL10', 'WWPR:WELL1A', 'WWPR:WELL1B', 'WWPR:WELL2', 'WWPR:WELL2A', 'WWPR:WELL3', 'WWPR:WELL3A', 'WWPR:WELL4', 'WWPR:WELL4A', 'WWPR:WELL5', 'WWPR:WELL5A', 'WWPR:WELL6', 'WWPR:WELL7', 'WWPR:WELL8', 'WWPR:WELL9']
['WGPR:WELL10', 'WGPR:WELL1B', 'WGPR:WELL2', 'WGPR:WELL2A', 'WGPR:WELL3', 'WGPR:WELL3A', 'WGPR:WELL4', 'WGPR:WELL4A', 'WGPR:WELL5', 'WGPR:WELL5A', 'WGPR:WELL6', 'WGPR:WELL7', 'WGPR:WELL8', 'WGPR:WELL9']
['FGPR        ', 'FOPR        ', 'FWCT        ', 'FWIR        ', 'FWPR        ']

In [15]:
regex = ['1$', '10$', '1A$', '1B$', '2$', '2A$', '3$', '3A$', '4$', '4A$', '5$', '5A$', '6$', '7$', '8$', '9$']
for i in regex:
    print(i, list(df_hist.filter(regex = i, axis = 1)))
    temp_list = list(df_hist.filter(regex = i, axis = 1))
    temp_df = df_hist.filter(items = temp_list)

1$ ['WBHP:WELL1', 'WOPR:WELL1', 'WWPR:WELL1']
10$ ['WBHP:WELL10', 'WOPR:WELL10', 'WWPR:WELL10', 'WGPR:WELL10']
1A$ ['WBHP:WELL1A', 'WOPR:WELL1A', 'WWPR:WELL1A', 'WGPR:WELL1A']
1B$ ['WBHP:WELL1B', 'WOPR:WELL1B', 'WWPR:WELL1B', 'WGPR:WELL1B']
2$ ['WBHP:WELL2', 'WOPR:WELL2', 'WWPR:WELL2', 'WGPR:WELL2']
2A$ ['WBHP:WELL2A', 'WOPR:WELL2A', 'WWPR:WELL2A', 'WGPR:WELL2A']
3$ ['WBHP:WELL3', 'WOPR:WELL3', 'WWPR:WELL3', 'WGPR:WELL3']
3A$ ['WBHP:WELL3A', 'WOPR:WELL3A', 'WWPR:WELL3A', 'WGPR:WELL3A']
4$ ['WBHP:WELL4', 'WOPR:WELL4', 'WWPR:WELL4', 'WGPR:WELL4']
4A$ ['WBHP:WELL4A', 'WOPR:WELL4A', 'WWPR:WELL4A', 'WGPR:WELL4A']
5$ ['WBHP:WELL5', 'WOPR:WELL5', 'WWPR:WELL5', 'WGPR:WELL5']
5A$ ['WBHP:WELL5A', 'WOPR:WELL5A', 'WWPR:WELL5A', 'WGPR:WELL5A']
6$ ['WBHP:WELL6', 'WOPR:WELL6', 'WWPR:WELL6', 'WGPR:WELL6']
7$ ['WBHP:WELL7', 'WOPR:WELL7', 'WWPR:WELL7', 'WGPR:WELL7']
8$ ['WBHP:WELL8', 'WOPR:WELL8', 'WWPR:WELL8', 'WGPR:WELL8']
9$ ['WBHP:WELL9', 'WOPR:WELL9', 'WWPR:WELL9', 'WGPR:WELL9']

In [16]:
# этот блок делает датафрейм который будет использоваться для кластеризации
# пропущенные значения BHP заменяются на предыдущие
# сохраняет в 'HIST.txt' который будем кластеризовать
df = pd.DataFrame()
temp_df = pd.DataFrame()
for i in regex:
    temp = df_hist.filter(regex = i, axis = 1)
    time = df_hist.loc[:, ['TIME']]
    temp = temp.append(time, ignore_index = True, sort = False)
    
    if len(list(temp)) < 5: # length equal to 4 for well 1
        temp_df = df_hist.filter(items = temp)
        temp['DATE'] = time
        temp_df['WELL'] = 'WELL' + i[:-1]
        columns = ['BHP', 'QOIL', 'QWAT', 'DATE', 'WELL']
        temp_df.columns = columns
        
    else: # length equal to 5 for all other wells
        temp_df = df_hist.filter(items = temp)
        temp['DATE'] = time
        temp_df['WELL'] = 'WELL' + i[:-1]
        columns = ['BHP', 'QOIL', 'QWAT', 'QGAS', 'DATE', 'WELL']
        temp_df.columns = columns
    df = df.append(temp_df, ignore_index = True, sort = True)
    
df = df.reindex(['DATE', 'WELL', 'QOIL', 'QWAT', 'QGAS', 'BHP'], axis=1)

# change days from start_date to date
start_date = datetime.date(2011, 1, 1)
date_list = df['DATE'].tolist()
for i in range(len(date_list)):
    date_list[i] = start_date + timedelta(days = date_list[i])
date_series = pd.Series(date_list)
df['DATE'] = date_series.values

# fills empty BHP value in a row on the previous one taking into account well
bhp_list = df['BHP'].tolist()
well_list = df['WELL'].tolist()
well = 'WELL1' # initial variable value
for i in range(len(bhp_list)):   
    if math.isnan(bhp_list[i]) == False:
        temp = bhp_list[i]
    if well_list[i] == well:
        bhp_list[i] = temp
    if well_list[i] != well:
        if bhp_list[i] == np.NaN:
            temp = np.NaN
        else: 
            temp = bhp_list[i] 
    well = well_list[i]
bhp_series = pd.Series(bhp_list)
df['BHP'] = bhp_series.values

# prepare QWAT list
qwat_list = df['QWAT'].tolist()
for i in range(len(qwat_list)):
    if qwat_list[i] == 0:
        qwat_list[i] = np.NaN
qwat_series = pd.Series(qwat_list)       
df['QWAT'] = qwat_series.values

# fills empty QWAT value in a row on the previous one taking into account well
qwat_list = df['QWAT'].tolist()
well_list = df['WELL'].tolist()
well = 'WELL1' # initial variable value
temp = 34.680479 # initial variable value
for i in range(len(qwat_list)):   
    if math.isnan(qwat_list[i]) == False:
        temp = qwat_list[i]
    if well_list[i] == well:
        qwat_list[i] = temp
    if well_list[i] != well:
        if bhp_list[i] == np.NaN:
            temp = np.NaN
        else: 
            temp = bhp_list[i] 
    well = well_list[i]
qwat_series = pd.Series(qwat_list)
df['QWAT'] = qwat_series.values

qoil_list = df['QOIL'].tolist()
for i in range(len(qoil_list)):
    if qoil_list[i] < 200:
        qoil_list[i] = np.NaN
qoil_series = pd.Series(qoil_list)
df['QOIL'] = qoil_series.values

df.to_csv('HIST.txt', sep = '\t', index = False)

#df.iloc[375:405, :] # check BHP/QWAT column
#df.iloc[190:200, :] # check BHP/QWAT column
#df.iloc[971:976, :] # check OIL column
df.head()

         DATE   WELL         QOIL       QWAT  QGAS          BHP
0  2011-02-01  WELL1  7946.073372  34.680479   NaN  2236.946357
1  2011-03-04  WELL1  8196.885023  34.680479   NaN  2236.946357
2  2011-04-04  WELL1  7888.974902  34.680479   NaN  2236.946357
3  2011-05-05  WELL1  8040.342778  29.393044   NaN  2236.946357
4  2011-06-05  WELL1  8206.164825   9.307177   NaN  2236.946357